### ISSUE TITLE
Check EU GDPR application to Aus?

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/ofnaus-issues#5]

**Comment by mkllnk** [comment]
I'm pretty sure this doesn't apply to us, because we don't have European customers. In theory they could sign up, but it's clearly a platform for buying local food in Australia.

**Comment by lin-d-hop** [comment]
Yeah seriously don't worry about it. UK users are worrying about it more than they should :-)

**Comment by kirstenalarsen** [comment]
thanks! I’ve just received so many emails from everyone about it that i thought i’d better check! I now consider it checked :)
